version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Thanhdat03!Pass123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build: ./backend/TrungTinElectronicsAPI
    container_name: trungtin-api
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      Jwt__Key: "super_super_secret_key_123456789"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=TrungTinElectronicsDB;User Id=sa;Password=Thanhdat03!Pass123;TrustServerCertificate=True;"

volumes:
  sql_data: